version: 2.1
orbs:
  python: circleci/python@2.0.3
jobs:
  build_and_test: # this can be any name you choose
    executor: python/default # use the default executor defined within the orb
    steps:
      - checkout # checkout source code
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run  pytest
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  build_docker:
    environment:
      IMAGE_NAME: eryk123/jenkins_env
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  push_docker:
    environment:
      IMAGE_NAME: eryk123/jenkins_env
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish DockerImage to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u eryk123 --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  test_my_app:
    jobs:
      - build_and_test
      - build_docker
      - push_docker:
          requires:
            - build_docker